blank_issues_enabled: false
contact_links:
  - name: Developer Support
    url: https://www.paypal-support.com/
    about: If you need help troubleshooting your integration, reach out to PayPal Support.
