package com.paypal.android.corepayments.analytics

// Ref: https://blog.klipse.tech/databook/2022/06/22/separate-code-from-data.html
internal data class AnalyticsEventData(
    val environment: String,
    val eventName: String,
    val timestamp: Long,
    val orderId: String?,
    val buttonType: String? = null,
    val appSwitchEnabled: Boolean? = null,
    val shopperSessionId: String? = null,
    val shopperSessionExpirationAt: String? = null,
    val matchedAuthenticationMethods: List<String>? = null,
    val appSwitchUrl: String? = null,
    val checkoutFallbackUrl: String? = null,
    val errorDescription: String? = null,
    val isCachedSession: Boolean? = null,
    val isVaultRequest: Boolean? = null,
    val endTime: Long? = null,
    val endpoint: String? = null,
    val presentationType: String? = null,
    val flow: String? = null,
    val appSwitchEligible: Boolean? = null,
    val ineligibleReason: String? = null,
    val merchantId: String? = null,
    val bnCode: String? = null,
    val clientId: String? = null,
    val userAction: String? = null,
    val paypalNativeAppInstalled: String? = null,
    val returnAppUrl: String? = null,
    val cancelAppUrl: String? = null,
    val fallbackSchemeUrl: String? = null,
)
