#!/usr/bin/env bash

function display_insufficent_params {
  echo "usage: ./create-order <CLIENT_ID> <CLIENT_SECRET>"
  echo "insufficient params"
}

CLIENT_ID="$1"
CLIENT_SECRET="$2"
ACCESS_TOKEN="$3"
ORDER_ID="$4"

if [ -z "${CLIENT_ID}" ] || [ -z "${CLIENT_SECRET}" ]; then
  display_insufficent_params
  exit 1
fi

#ACCESS_TOKEN=$(./get-auth-token "${CLIENT_ID}" "${CLIENT_SECRET}" | jq -r '.access_token')

CONFIRM_PAYMENT_URL="https://api.sandbox.paypal.com/v2/checkout/orders/${ORDER_ID}/confirm-payment-source"
CREDENTIALS=$(echo -n "${CLIENT_ID}:${CLIENT_SECRET}" | base64)

echo $CONFIRM_PAYMENT_URL

curl -s --location -g --request POST "${CONFIRM_PAYMENT_URL}" \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer ${ACCESS_TOKEN}" \
--data-raw '{
  "payment_source": {
    "card": {
      "number": "4000000000000002",
      "expiry": "2023-01",
      "name": "John Doe",
      "security_code": "123",
      "billing_address": {
        "address_line_1": "2211 N First Street",
        "address_line_2": "17.3.160",
        "admin_area_1": "San Jose",
        "admin_area_2": "CA",
        "postal_code": "95131",
        "country_code": "US"
      },
      "attributes": {
        "verification": {
          "method": "SCA_ALWAYS"
        }
      }
    }
  }
}' | jq
