#!/usr/bin/env bash

function display_insufficent_params {
  echo "usage: ./create-order <CLIENT_ID> <CLIENT_SECRET>"
  echo "insufficient params"
}

CLIENT_ID="$1"
CLIENT_SECRET="$2"

if [ -z "${CLIENT_ID}" ] || [ -z "${CLIENT_SECRET}" ]; then
  display_insufficent_params
  exit 1
fi

ACCESS_TOKEN=$(./get-access-token "${CLIENT_ID}" "${CLIENT_SECRET}" | jq -r '.access_token')

ORDER_URL="https://api.sandbox.paypal.com/v2/checkout/orders"
CREDENTIALS=$(echo -n "${CLIENT_ID}:${CLIENT_SECRET}" | base64)

curl -s --location -g --request POST "${ORDER_URL}" \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer ${ACCESS_TOKEN}" \
--data-raw '{
    "intent": "CAPTURE",
    "purchase_units": [
        {
            "amount": {
                "currency_code": "USD",
                "value": "56.00"
            }
        }
    ]
}' | jq
