#!/usr/bin/env bash

function display_insufficent_params {
  echo "usage: ./get-auth-token <CLIENT_ID> <CLIENT_SECRET>"
  echo "insufficient params"
}

CLIENT_ID="$1"
CLIENT_SECRET="$2"

if [ -z "${CLIENT_ID}" ] || [ -z "${CLIENT_SECRET}" ]; then
  display_insufficent_params
  exit 1
fi

TOKEN_URL="http://localhost:8080/v1/oauth2/token"
CREDENTIALS=$(echo -n "${CLIENT_ID}:${CLIENT_SECRET}" | base64)

curl -s --location -g --request POST "${TOKEN_URL}" \
  --header "Authorization: Basic ${CREDENTIALS}" \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'grant_type=client_credentials'
