name: Build
on: [pull_request, workflow_dispatch]
concurrency:
  group: build-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  build_aar:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Assemble
        run: ./gradlew --stacktrace assemble -x :Demo:assemble # we exclude Demo module in assemble
