name: Test Coverage
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: test-coverage-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  test_coverage_job:
    name: Test Code Coverage
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Generate Code Coverage Reports
        run: ./gradlew jacocoTestReport
      - name: Upload Core coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov -f Core/build/jacoco/jacoco.xml -F core
      - name: Upload CardPayments coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov -f CardPayments/build/jacoco/jacoco.xml -F card
